version: '3'
services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        command: ["yarn", "dev"]
        volumes:
            - ./:/var/www/html:cached
        working_dir: /var/www/html
        tty: true
        user: ${CURRENT_USER}
